# Rust formatting configuration (stable features only)
# Similar to Prettier for JavaScript

# Basic configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Chain formatting
chain_width = 60
single_line_if_else_max_width = 50

# Imports
reorder_imports = true
reorder_modules = true

# Field and method chains
use_field_init_shorthand = true
use_try_shorthand = true

# Small heuristics for better formatting
use_small_heuristics = "Default"

# Match formatting  
match_block_trailing_comma = true